dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  # file_picker を最新バージョンに更新
  file_picker: ^8.0.0+1  # 最新バージョンに更新
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7